BRINSA/WebCilindros/WebCilindros/Controllers/MenuController.cs
using System.Web.Mvc;

namespace WebCilindros.Controllers
{
    public class MenuController : Controller
    {
        
        public ActionResult _Menu()
        {
            return PartialView();
        }
    }
}

BRINSA/WebCilindros/WebCilindros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Web Cilindros</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")

    @Styles.Render("~/Content/StyleModalDragDrop.css")
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
</head>
<body style="background-color:@System.Configuration.ConfigurationManager.AppSettings["BackApp"]">
    @*<div id="HMENU">
        @Html.Action("_Menu", "Menu")
    </div>*@

    <div class="container body-content">
        @RenderBody()
    </div>

    <div class="footer">
        <div>
            <img src="~/Content/img/LogoBSS1.png" />
            <label>Desarrollado por BSS Ltda.&copy; @DateTime.Now.Year - Web Cilindros</label>
        </div>
    </div>

    <div class="alineadoCentro">
        <div id="fondo" class="foscuro oculto">
            <div class="contespera">
                <div>
                    <img src="~/Content/img/DRing.svg" />
                </div>
            </div>
        </div>

        <div id="myModMsg" class="modalu">
            <div class="fondomodal">
            </div>
            <div class="modal-dialogu">
                <div class="modal-content fondoBody">
                    <div class="modal-header">
                        <button id="cerrarModMsg" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Web Cilindros</h4>
                    </div>
                    <div class="modal-body">
                        <label id="LblMsg" style="margin-top:20px;"></label>
                    </div>
                    <div class="modal-footer">
                        <button id="cancelModMsg" type="button" class="btn btn-default" data-dismiss="modal">Aceptar</button>
                    </div>
                </div>
            </div>
        </div>

    </div>

    @Html.EJ().ScriptManager()
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @Styles.Render("~/Content/jquery-ui.css")
    @Scripts.Render("~/Scripts/jquery-ui.js")
    @Scripts.Render("~/Scripts/JSModal.js")

    <script type="text/javascript">
        var intervaloFiltro;

        function ValidaFiltro() {
            var elemento = document.querySelector("li[ejfnrole='filterpopup']");
            console.log("Prueba");
            if (elemento != null) {
                elemento.setAttribute("class", "oculto");
                window.clearInterval(intervaloFiltro);
            }
        }

        function AComplete(args) {
            $("#fondo").addClass("oculto");
            if (args.requestType == "filterafteropen") {
                intervaloFiltro = window.setInterval(ValidaFiltro, 600);
            }
        }

        function CreatePagination(id) {
            var tdStr = '';

            tdStr += '<div id="pagers" class="npag">';
            tdStr += '<select onchange="sizeValChange(this, ' + id + ')" class="form-control input-sm" style="width:70px;">';
            tdStr += '<option>15</option>';
            tdStr += '<option>25</option>';
            tdStr += '<option>50</option>';
            tdStr += '<option>100</option>';
            tdStr += '</select>';
            tdStr += '</div>';

            $('#' + id + ' div > div.e-pagercontainer').after(tdStr);
        }

        function setPageValue(id, val) {
            $("#" + id).ejNumericTextbox("model").maxValue = val;
        }

        function checkNumericValue(value, grilla) {
            var pagermodel = $("#" + grilla.id).ejGrid("getPager").ejPager("model");
            return (value == "" || value == 0);
        }

        function sizeValChange(args, grilla) {
            if (checkNumericValue(args.value, grilla.id))
                return;
            var model = $("#" + grilla.id).ejGrid("model");
            var model1 = $("#" + grilla.id).ejGrid("getPager").ejPager("model");
            var newLastPage = Math.ceil(model.pageSettings.totalRecordsCount / args.value);
            $("#" + grilla.id).ejGrid({ "pageSettings": { pageSize: parseInt(args.value) } });
            if (model1.pageCount > newLastPage)
                $("#counttxt").ejNumericTextbox({ value: newLastPage });
            else {
                setPageValue("pagetxt", model1.totalPages);
                $("#counttxt").ejNumericTextbox({ value: model1.pageCount });
                flag = true;
                $("#pagetxt").ejNumericTextbox({ value: model1.currentPage });
                flag = false;
            }
        }

        $(window).resize(function () {
            $(".modal-body").css("max-height", ($(window).height() - 200) + "px");
        });

                //$(document).ready(function () {

                //});
    </script>
</body>
</html>